mbx: Automate Storage management - SysVM template download & seeding (#19)
mbx launch now creates systemvmtemplate cache and seeds template
to secondary storage if necessary before launching zone

Signed-off-by: Rohit Yadav <rohit.yadav@shapeblue.com>
Co-authored-by: Rohit Yadav <rohit.yadav@shapeblue.com>

diff --git a/mbx b/mbx
--- a/mbx
+++ b/mbx
@@ -21,17 +21,17 @@ ROOT="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
 mkdir -p $ROOT/boxes
 touch $ROOT/boxes/boxes.list
 export LIBVIRT_DEFAULT_URI="qemu:///system"
-echo MonkeyBox 🐵 v0.1
+echo MonkeyBox 🐵 v0.2
 
 usage() {
   echo "Available commands are:"
   echo "   init: initialises monkeynet and mbx templates"
   echo "   package: builds packages from a git repo and sha/tag/branch"
   echo "   list: lists available environments"
-  echo "   deploy: deploys QA env with two monkeybox VMs, configures storage, creates marvin cfg file"
+  echo "   deploy: creates QA env with two monkeybox VMs and creates marvin cfg file"
   echo "   launch: launches QA env zone using environment's marvin cfg file"
   echo "   test: start marvin tests"
-  echo "   dev: deploys dev env with a single monkeybox VM, configures storage, creates marvin cfg file"
+  echo "   dev: creates dev env with a single monkeybox VM and creates marvin cfg file"
   echo "   agentscp: updates KVM agent in dev environment using scp and restarts it"
   echo "   ssh: ssh into a mbx VM"
   echo "   stop: stop all env VMs"
@@ -157,22 +157,46 @@ check_mbxt() {
 }
 
 issh() {
-  sshpass -p 'P@ssword123' ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" $@
+  sshpass -p 'P@ssword123' ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" -o "LogLevel=ERROR" $@
 }
 
 iscp() {
-  sshpass -p 'P@ssword123' scp -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" $@
+  sshpass -p 'P@ssword123' scp -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" -o "LogLevel=ERROR" $@
+}
+
+seed_systemvmtemplate() {
+  version=$1
+  hypervisor=$2
+  sstore_path=$3
+  cache_path=/export/monkeybox/templates/cache/$version/$hypervisor
+  url=$(cat $ROOT/files/systemvm-map.json | jq -r ".[\"${version}\"].${hypervisor}.url")
+  checksum=$(cat $ROOT/files/systemvm-map.json | jq -r ".[\"${version}\"].${hypervisor}.checksum")
+  template_path=$cache_path/${url##*/}
+  mkdir -p $cache_path
+  wget -nc $url -O $template_path || true
+  if [[ "$(md5sum $template_path | awk '{print $1}')" != "$checksum" ]]; then
+    rm -f $template_path
+    echo "The systemvmtemplate cache is invalid, removed old cache, please re-run launch command"
+    exit 1
+  fi
+  echo "Seeding v$version systemvmtemplate for '$hypervisor' at $sstore_path"
+  if [[ "$hypervisor" == "xen" || "$hypervisor" == "xcp" ]]; then
+    hypervisor="xenserver"
+  fi
+  if [[ "$hypervisor" == "vmw" ]]; then
+    hypervisor="vmware"
+  fi
+  sudo /export/monkeybox/files/setup-systemvmtemplate.sh -m $sstore_path -f $template_path -h $hypervisor -F
 }
 
 deploy() {
   if [[ "$1" == "-h" ]]; then
-    echo "Usage: mbx deploy <name of env> <mgmt server template> <hypervisor template> <repo> <storage source>"
+    echo "Usage: mbx deploy <name of env> <mgmt server template> <hypervisor template> <repo url>"
     exit 0
   fi
 
-  set -x
   id=
-  for idx in {1..9}; do
+  for idx in {1..20}; do
     if ! grep -q qa$idx- $ROOT/boxes/boxes.list; then
       id=$idx
       break
@@ -183,27 +207,24 @@ deploy() {
     exit 1
   fi
 
-  name=${1:-"mbxe"}
+  name=${1:-"mbx-cs415"}
   mst=${2:-"mbxt-kvm-centos7"}
   hyt=${3:-"mbxt-kvm-centos7"}
-  # Validate input templates
+  # Validate templates
   check_mbxt mgmt $mst
   check_mbxt hypervisor $hyt
-
   hypervisor=$(echo $hyt |  awk '{print substr($0,6,3)}')
   repo=${4:-"http://packages.shapeblue.com/cloudstack/upstream/centos7/4.15"}
-  storage=${5:-"/export/testing/4.15"}
+
   uuid=$(cat /proc/sys/kernel/random/uuid | sed 's/-.*//g')
   env="qa$id-$name-$uuid-$hypervisor"
 
   echo -e "Building env with name: \033[4m$env\033[0m"
   echo "Management server template: $mst"
   echo "Hypervisor template: $hyt"
-  echo "Repository: $repo"
-  echo "Storage source: $storage"
+  echo "Package repo: $repo"
 
   mkdir -p $ROOT/boxes/$env
-  # Save env name
   echo $env >> $ROOT/boxes/boxes.list
 
   # Clone mgmt server
@@ -230,14 +251,12 @@ deploy() {
   echo "Starting VMs"
   for domain in $(cat $ROOT/boxes/$env/list); do virsh start $domain; done;
 
-  echo "Copying primary and secondary storages"
-  env_storage="/export/testing/$env/"
-  sudo cp -vr $storage $env_storage
+  echo "Creating primary and secondary storage folders"
+  sudo mkdir -p /export/testing/$env/{primary1,primary2,secondary}
   sync
-  echo "Primary and secondary storages are ready"
 
-  echo "Initialising environment hosts"
-  sleep 30
+  echo "Waiting for hosts to boot... (this can take a few minutes)"
+  sleep 60
   for box in $(cat $ROOT/boxes/$env/list); do
     echo "Configuring host $box"
     ip=$(getent hosts $box | awk '{ print $1 }')
@@ -337,6 +356,7 @@ deploy() {
   if [[ $hypervisor == "xcp" ]]; then
     hypervisor="xen"
   fi
+  echo $hypervisor > $ROOT/boxes/$env/hypervisor
 
   # Find VC IP
   export vcip=
@@ -368,7 +388,6 @@ deploy() {
 }
 
 launch() {
-  set -x
   env=$1
   if [ -z $env ]; then
     echo "Please provide a valid env name, run 'mbx list' to find name of environments"
@@ -382,7 +401,7 @@ launch() {
   iscp $ROOT/boxes/$env/marvin.cfg root@$msip:/marvin/
   iscp $ROOT/files/smoketests.sh root@$msip:/marvin/
   iscp $ROOT/files/result.py root@$msip:/marvin/
-  while ! nc -vzw 5 $msip 8096 2>&1 > /dev/null; do echo "Waiting for management server to come up"; sleep 10; done
+  while ! nc -vzw 5 $msip 8096 2>&1 > /dev/null; do echo "Waiting for management server to come up..."; sleep 10; done
   issh root@$msip systemctl start cloudstack-usage
   issh root@$msip "mysql -u root --execute=\"UPDATE cloud.service_offering set ram_size=512 where vm_type='consoleproxy';\""
   echo "Management server is UP now, launching data center now"
@@ -392,6 +411,13 @@ launch() {
     issh root@$msip "pip3 install /usr/share/cloudstack-marvin/Marvin*.tar.gz"
     issh root@$msip "python3 /usr/local/lib/python3.6/site-packages/marvin/deployDataCenter.py -i /marvin/marvin.cfg"
   else
+    if echo "4.9 4.11 4.12 4.13 4.14 4.15" | grep -w $version > /dev/null; then
+      hypervisor=$(cat $ROOT/boxes/$env/hypervisor)
+      seed_systemvmtemplate $version $hypervisor /export/testing/$env/secondary
+    else
+        echo "Unsupported ACS version $version, please manually seed the systemvmtemplate and deploy the zone"
+        exit 1
+    fi
     issh root@$msip "pip2 install /usr/share/cloudstack-marvin/Marvin*.tar.gz"
     issh root@$msip "python /usr/lib/python2.7/site-packages/marvin/deployDataCenter.py -i /marvin/marvin.cfg"
   fi
@@ -410,7 +436,7 @@ test() {
 
 dev() {
   if [[ "$1" == "-h" ]]; then
-    echo "Usage: mbx dev <name of env> <hypervisor template> <storage source>"
+    echo "Usage: mbx dev <name of env> <hypervisor template>"
     exit 0
   fi
 
@@ -433,12 +459,10 @@ dev() {
   check_mbxt hypervisor $hyt
 
   hypervisor=$(echo $hyt |  awk '{print substr($0,6,3)}')
-  storage=${3:-"/export/testing/4.15"}
   env="dev$id-$name-$hypervisor"
 
   echo -e "Building dev env with name: \033[4m$env\033[0m"
   echo "Hypervisor template: $hyt"
-  echo "Storage source: $storage"
 
   mkdir -p $ROOT/boxes/$env
   # Save env name
@@ -455,13 +479,11 @@ dev() {
   echo "Starting VMs"
   for domain in $(cat $ROOT/boxes/$env/list); do virsh start $domain; done;
 
-  echo "Copying primary and secondary storages"
-  env_storage="/export/testing/$env/"
-  sudo cp -vr $storage $env_storage
+  echo "Creating primary and secondary storage folders"
+  sudo mkdir -p /export/testing/$env/{primary1,primary2,secondary}
   sync
-  echo "Primary and secondary storages are ready"
 
-  echo "Initialising dev hosts"
+  echo "Waiting for dev host to boot"
   sleep 60
   for box in $(cat $ROOT/boxes/$env/list); do
     echo "Configuring host $box"
@@ -638,9 +660,9 @@ destroy() {
     virsh destroy $vm 2> /dev/null || true;
     virsh undefine $vm;
   done
-  sync
   sed -i "/$env/d" $ROOT/boxes/boxes.list
   rm -fr $ROOT/boxes/$env
+  sync
   sudo rm -fr /export/testing/$env
 }
 
