Automate Storage management - SysVM template download & seeding

diff --git a/mbx b/mbx
--- a/mbx
+++ b/mbx
@@ -164,9 +164,72 @@ iscp() {
   sshpass -p 'P@ssword123' scp -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" $@
 }
 
+seed_template() {
+  sec_store_path=$1/secondary/
+  template_name=$2
+  hypervisor=$3
+  script="sudo /export/monkeybox/files/setup-systemvmtemplate.sh -m $sec_store_path -f $1/$template_name -h $hypervisor"
+  output=$(eval $script)
+  if [ ! -n "$(echo "$output" | grep "Success")" ] && [ -n "$(echo "$output" | grep "failed")" ] ; then
+    echo "Failed to seed the template. Please try again."
+    exit 1
+  fi
+}
+
+setup_storage() {
+  acs_version=$1
+  local hypervisor=$2
+  ver=$(echo "${acs_version//./}")
+  stg_path="/export/testing"
+  basepath=${stg_path}/${acs_version}
+  sudo mkdir -p ${basepath}/{primary1,primary2,secondary}
+  chksum_url=$(cat ./files/hyp-os-map.json | jq -r .cs${ver}.md5sum)
+  if [ ! -f ${basepath}/md5sum.txt ]; then
+    sudo wget --show-progress -nc $chksum_url -O ${basepath}/md5sum.txt
+  fi
+
+  if [ ! -f ${basepath}/md5sum.txt ]; then
+    echo "Failed to download md5sum file. Please try to download it manually"
+    exit 1
+  fi
+
+  if [[ "$hypervisor" == "kvm" ]]; then
+    template_url=$(cat $ROOT/files/hyp-os-map.json | jq -r .cs${ver}.kvm)
+    hypv="kvm"
+  elif [[ "$hypervisor" == "vmw" ]]; then
+    template_url=$(cat $ROOT/files/hyp-os-map.json | jq -r .cs${ver}.vmware)
+    hypv="vmware"
+  elif [[ "$hypervisor" == "xen" ]] || [[ "$hypervisor" == "xcp" ]]; then
+    template_url=$(cat $ROOT/files/hyp-os-map.json | jq -r .cs${ver}.xs)
+    hypv="xenserver"
+  else
+    echo "Failed to get the template URL for the specified hypervisor. Please check if the hypervisor type is supported"
+    exit 1
+  fi
+
+  template_name=${template_url##*/}
+  if [ ! -f ${basepath}/${template_name} ]; then
+    sudo wget --show-progress -nc $template_url -O ${basepath}/${template_name}
+    cd $basepath
+    file_cnt=$(ls | wc -l)
+    tmp_cnt=$(( file_cnt - 4 ))
+    md5sumchk=$(sudo md5sum --check ${basepath}/md5sum.txt --ignore-missing)
+    temps_validated=$(echo "$md5sumchk" | wc -l )
+    # validate if the number of templates present in the storage directory  
+    # corresponds to the number of validations performed by 'md5sum --check'
+    if [ "$temps_validated" -lt "$tmp_cnt" ] || [[ -n "$(echo $md5sumchk | grep "FAILED")" ]]; then
+      echo "Failed to download required template(s) or checksum validation failed. Exiting..."
+      exit 1
+    fi
+  fi
+  echo "Seeding template"
+  seed_template $basepath $template_name $hypv
+  cd -
+}
+
 deploy() {
   if [[ "$1" == "-h" ]]; then
-    echo "Usage: mbx deploy <name of env> <mgmt server template> <hypervisor template> <repo> <storage source>"
+    echo "Usage: mbx deploy <name of env> <mgmt server template> <hypervisor template> <repo>"
     exit 0
   fi
 
@@ -192,7 +255,6 @@ deploy() {
 
   hypervisor=$(echo $hyt |  awk '{print substr($0,6,3)}')
   repo=${4:-"http://packages.shapeblue.com/cloudstack/upstream/centos7/4.15"}
-  storage=${5:-"/export/testing/4.15"}
   uuid=$(cat /proc/sys/kernel/random/uuid | sed 's/-.*//g')
   env="qa$id-$name-$uuid-$hypervisor"
 
@@ -200,7 +262,12 @@ deploy() {
   echo "Management server template: $mst"
   echo "Hypervisor template: $hyt"
   echo "Repository: $repo"
-  echo "Storage source: $storage"
+
+  repo=${repo%/}
+  acs_version=${repo##*/}
+  os=${hyt##*-}
+  storage="/export/testing/"${acs_version}
+  setup_storage $acs_version $hypervisor
 
   mkdir -p $ROOT/boxes/$env
   # Save env name
